### ISSUE TITLE
Update Substrate dependencies to use crates.io versions

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#20]
With the v2.0 freeze that happened in Substrate today we'll hopefully be seeing a lot of crates get published to crates.io soon. We'll need to update our dependencies to use that instead of pulling from git.

**Comment by tomusdrw** [comment]
we already do that I believe.

**Comment by svyatonik** [comment]
> we already do that I believe.

I'm not sure - Wwe still have something like that all across the codebase:
```toml
[dependencies.frame-support]
version = "2.0.0-rc6"
tag = 'v2.0.0-rc6'
default-features = false
git = "https://github.com/paritytech/substrate/"
```
